//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainClient.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MainClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 [
        ///    {
        ///        &quot;code&quot;: &quot;110000&quot;,
        ///        &quot;province&quot;: &quot;北京市&quot;,
        ///        &quot;city&quot;: &quot;全部&quot;
        ///    },
        ///    {
        ///        &quot;code&quot;: &quot;110000&quot;,
        ///        &quot;province&quot;: &quot;北京市&quot;,
        ///        &quot;city&quot;: &quot;北京市&quot;
        ///    },
        ///    {
        ///        &quot;code&quot;: &quot;120000&quot;,
        ///        &quot;province&quot;: &quot;天津市&quot;,
        ///        &quot;city&quot;: &quot;全部&quot;
        ///    },
        ///    {
        ///        &quot;code&quot;: &quot;120000&quot;,
        ///        &quot;province&quot;: &quot;天津市&quot;,
        ///        &quot;city&quot;: &quot;天津市&quot;
        ///    },
        ///    {
        ///        &quot;code&quot;: &quot;130000&quot;,
        ///        &quot;province&quot;: &quot;河北省&quot;,
        ///        &quot;city&quot;: &quot;全部&quot;
        ///    },
        ///    {
        ///        &quot;code&quot;: &quot;130100&quot;,
        ///        &quot;prov [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string region_1 {
            get {
                return ResourceManager.GetString("region_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [{
        ///		&quot;code&quot;: &quot;110000&quot;,
        ///		&quot;province&quot;: &quot;北京市&quot;,
        ///		&quot;city&quot;: &quot;北京&quot;
        ///	},
        ///	{
        ///		&quot;code&quot;: &quot;120000&quot;,
        ///		&quot;province&quot;: &quot;天津市&quot;,
        ///		&quot;city&quot;: &quot;天津&quot;
        ///	},
        ///	{
        ///		&quot;code&quot;: &quot;130000&quot;,
        ///		&quot;province&quot;: &quot;河北省&quot;,
        ///		&quot;city&quot;: &quot;河北&quot;
        ///	},
        ///	{
        ///		&quot;code&quot;: &quot;130100&quot;,
        ///		&quot;province&quot;: &quot;河北省&quot;,
        ///		&quot;city&quot;: &quot;石家庄&quot;
        ///	},
        ///	{
        ///		&quot;code&quot;: &quot;130200&quot;,
        ///		&quot;province&quot;: &quot;河北省&quot;,
        ///		&quot;city&quot;: &quot;唐山&quot;
        ///	},
        ///	{
        ///		&quot;code&quot;: &quot;130300&quot;,
        ///		&quot;province&quot;: &quot;河北省&quot;,
        ///		&quot;city&quot;: &quot;秦皇岛&quot;
        ///	},
        ///	{
        ///		&quot;code&quot;: &quot;130400&quot;,
        ///		&quot;province&quot;: &quot;河北省&quot;,
        ///		&quot;city&quot;: &quot;邯郸&quot;
        ///	},
        ///	{
        ///		&quot;code&quot;: &quot;130500&quot;,
        ///		&quot;provin [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string region_2 {
            get {
                return ResourceManager.GetString("region_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [
        ///    {
        ///        &quot;code&quot;: &quot;340800&quot;,
        ///        &quot;province&quot;: &quot;安徽省&quot;,
        ///        &quot;city&quot;: &quot;安庆市&quot;
        ///    },
        ///    {
        ///        &quot;code&quot;: &quot;340300&quot;,
        ///        &quot;province&quot;: &quot;安徽省&quot;,
        ///        &quot;city&quot;: &quot;蚌埠市&quot;
        ///    },
        ///    {
        ///        &quot;code&quot;: &quot;341600&quot;,
        ///        &quot;province&quot;: &quot;安徽省&quot;,
        ///        &quot;city&quot;: &quot;亳州市&quot;
        ///    },
        ///    {
        ///        &quot;code&quot;: &quot;341100&quot;,
        ///        &quot;province&quot;: &quot;安徽省&quot;,
        ///        &quot;city&quot;: &quot;滁州市&quot;
        ///    },
        ///    {
        ///        &quot;code&quot;: &quot;341200&quot;,
        ///        &quot;province&quot;: &quot;安徽省&quot;,
        ///        &quot;city&quot;: &quot;阜阳市&quot;
        ///    },
        ///    {
        ///        &quot;code&quot;: &quot;340100&quot;,
        ///        &quot;p [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string region_3 {
            get {
                return ResourceManager.GetString("region_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [
        ///    {
        ///        &quot;code&quot;: &quot;214&quot;,
        ///        &quot;province&quot;: &quot;北京市&quot;
        ///    },
        ///    {
        ///        &quot;code&quot;: &quot;234&quot;,
        ///        &quot;province&quot;: &quot;天津市&quot;
        ///    },
        ///    {
        ///        &quot;code&quot;: &quot;254&quot;,
        ///        &quot;province&quot;: &quot;河北省&quot;
        ///    },
        ///    {
        ///        &quot;code&quot;: &quot;433&quot;,
        ///        &quot;province&quot;: &quot;山西省&quot;
        ///    },
        ///    {
        ///        &quot;code&quot;: &quot;559&quot;,
        ///        &quot;province&quot;: &quot;内蒙古自治区&quot;
        ///    },
        ///    {
        ///        &quot;code&quot;: &quot;673&quot;,
        ///        &quot;province&quot;: &quot;辽宁省&quot;
        ///    },
        ///    {
        ///        &quot;code&quot;: &quot;786&quot;,
        ///        &quot;province&quot;: &quot;吉林省&quot;
        ///    },
        ///    {
        ///        &quot;code&quot;: &quot;853&quot;,
        ///        &quot;prov [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string region_4_1 {
            get {
                return ResourceManager.GetString("region_4_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [
        ///    {
        ///        &quot;code&quot;: &quot;215&quot;,
        ///        &quot;city&quot;: &quot;北京市&quot;
        ///    },
        ///    {
        ///        &quot;code&quot;: &quot;235&quot;,
        ///        &quot;city&quot;: &quot;天津市&quot;
        ///    },
        ///    {
        ///        &quot;code&quot;: &quot;255&quot;,
        ///        &quot;city&quot;: &quot;石家庄市&quot;
        ///    },
        ///    {
        ///        &quot;code&quot;: &quot;279&quot;,
        ///        &quot;city&quot;: &quot;唐山市&quot;
        ///    },
        ///    {
        ///        &quot;code&quot;: &quot;294&quot;,
        ///        &quot;city&quot;: &quot;秦皇岛市&quot;
        ///    },
        ///    {
        ///        &quot;code&quot;: &quot;302&quot;,
        ///        &quot;city&quot;: &quot;邯郸市&quot;
        ///    },
        ///    {
        ///        &quot;code&quot;: &quot;322&quot;,
        ///        &quot;city&quot;: &quot;邢台市&quot;
        ///    },
        ///    {
        ///        &quot;code&quot;: &quot;340&quot;,
        ///        &quot;city&quot;: &quot;保定市&quot;
        ///    },
        ///    {
        ///     [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string region_4_2 {
            get {
                return ResourceManager.GetString("region_4_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [
        ///    {
        ///        &quot;provinceCode&quot;: &quot;110000&quot;,
        ///        &quot;provinceName&quot;: &quot;北京&quot;,
        ///        &quot;mallCityList&quot;: [
        ///            {
        ///                &quot;cityCode&quot;: &quot;110100&quot;,
        ///                &quot;cityName&quot;: &quot;北京&quot;
        ///            }
        ///        ]
        ///    },
        ///    {
        ///        &quot;provinceCode&quot;: &quot;120000&quot;,
        ///        &quot;provinceName&quot;: &quot;天津&quot;,
        ///        &quot;mallCityList&quot;: [
        ///            {
        ///                &quot;cityCode&quot;: &quot;120100&quot;,
        ///                &quot;cityName&quot;: &quot;天津&quot;
        ///            }
        ///        ]
        ///    },
        ///    {
        ///        &quot;provinceCode&quot;: &quot;130000&quot;,
        ///        &quot;provinceName&quot;: [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string region_51daili {
            get {
                return ResourceManager.GetString("region_51daili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [
        ///    {
        ///       &quot;code&quot;:&quot;120000&quot;,
        ///       &quot;name&quot;:&quot;天津&quot;
        ///    },
        ///    {
        ///       &quot;code&quot;:&quot;130000&quot;,
        ///       &quot;name&quot;:&quot;河北省&quot;
        ///    },
        ///    {
        ///       &quot;code&quot;:&quot;140000&quot;,
        ///       &quot;name&quot;:&quot;山西省&quot;
        ///    },
        ///    {
        ///       &quot;code&quot;:&quot;150000&quot;,
        ///       &quot;name&quot;:&quot;内蒙古自治区&quot;
        ///    },
        ///    {
        ///       &quot;code&quot;:&quot;210000&quot;,
        ///       &quot;name&quot;:&quot;辽宁省&quot;
        ///    },
        ///    {
        ///       &quot;code&quot;:&quot;220000&quot;,
        ///       &quot;name&quot;:&quot;吉林省&quot;
        ///    },
        ///    {
        ///       &quot;code&quot;:&quot;230000&quot;,
        ///       &quot;name&quot;:&quot;黑龙江省&quot;
        ///    },
        ///    {
        ///       &quot;code&quot;:&quot;310000&quot;,
        ///       &quot;name&quot;:&quot;上海&quot;
        ///    },
        ///    {
        ///       &quot;code [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string region_ipzan {
            get {
                return ResourceManager.GetString("region_ipzan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [
        ///    {
        ///        &quot;code&quot;: &quot;210000&quot;,
        ///        &quot;name&quot;: &quot;辽宁&quot;
        ///    },
        ///    {
        ///        &quot;code&quot;: &quot;211300&quot;,
        ///        &quot;name&quot;: &quot; 朝阳&quot;
        ///    },
        ///    {
        ///        &quot;code&quot;: &quot;210200&quot;,
        ///        &quot;name&quot;: &quot; 大连&quot;
        ///    },
        ///    {
        ///        &quot;code&quot;: &quot;210800&quot;,
        ///        &quot;name&quot;: &quot; 营口&quot;
        ///    },
        ///    {
        ///        &quot;code&quot;: &quot;210900&quot;,
        ///        &quot;name&quot;: &quot; 阜新&quot;
        ///    },
        ///    {
        ///        &quot;code&quot;: &quot;211400&quot;,
        ///        &quot;name&quot;: &quot; 葫芦岛&quot;
        ///    },
        ///    {
        ///        &quot;code&quot;: &quot;211000&quot;,
        ///        &quot;name&quot;: &quot; 辽阳&quot;
        ///    },
        ///    {
        ///        &quot;code&quot;: &quot;211200&quot;,
        ///        &quot;name&quot;: &quot; 铁岭 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string region_shenlong {
            get {
                return ResourceManager.GetString("region_shenlong", resourceCulture);
            }
        }
    }
}
